### ISSUE TITLE
Flash sonoff with mongoose os via wifi

### ISSUE THREAD

**Issue by trikon** [mongoose-os-apps/sonoff-basic-openhab#6]
Tell me please, is it possible to flash sonoff with mongoose os via wifi without any wires?
Or how i can generate .bin with MOS file and upload it with OTA mechanism?
Thanks, for help.

**Comment by michaelfung** [comment]
You can't because sonoff has only 1MBytes flash chip.

**Comment by trikon** [comment]
but this project is about MOS on sonoff devices:)
