### ISSUE TITLE
Changes to build under newer releases

### ISSUE THREAD

**Issue by scaprile** [mongoose-os-apps/sonoff-basic-openhab#7]
Hi, 
mos.yml requires a manifest_version entry
`manifest_version: 2017-05-18`
and main.c requires changes in the include paths:
```
#include "mgos_app.h"
#include "mgos_gpio.h"
#include "mgos_sys_config.h"
#include "mgos_timers.h"
#include "mgos_hal.h"
#include "mgos_dlsym.h"
#include "mgos_mqtt.h"
#include "mjs.h"
#include "common/cs_dbg.h"
```
The OpenHAB example setup works on 1.x bindings, the newer 2.4+ mqtt binding with the things binding requires you to setup a broker, then add a Generic MQTT Thing, then a channel, and then you can setup your switch item:
```
Switch Bedroom_Lights_Switch {channel="mqtt:topic:mythingid:mychannelid"}
```
All other items are a bit more involved and I guess at this time following one of the supported conventions for autodiscovery is worth it.
Regards

**Comment by rojer** [comment]
please send a PR with these changes

**Comment by rojer** [comment]
PR merged, thank you!
