### ISSUE TITLE
Autodiscovery on openHAB 2.4+

### ISSUE THREAD

**Issue by scaprile** [mongoose-os-apps/sonoff-basic-openhab#9]
Hi,
I have modified init.js so the device announces and behaves according to the Homie convention 4.0.0. This way, openHAB automatically discovers the thing and channels are added with just a mouse click.
Even though modifications in init.js can be considered trivial, the openHAB part of the example will not work with this new code, and reworking it or providing for dual functionality will require some time I can't devote to it. (Some users still run the 1.x binding and don't care about auto-discovery) 
I wonder if branching this example is possible. Otherwise, I can just publish a fork with my mods on my account and let a comment pointing to it here.
Regards

**Comment by rojer** [comment]
i haven't worked with sonoff stuff and i have to admit, i have no idea what you're talking about :)
i vaguely understand that you adapted application for new their API version of the service, right?
if so, i think it's entirely appropriate for example to be converted to new API.

**Comment by scaprile** [comment]
It is a bit more complicated.
Sonoff: the hardware, we discard everything else
openHAB: the Home Automation Bus. The brains.
Homie convention: a way to arrange MQTT topics in order for devices to be autodiscovered and handled with minimum coding.
(binding)API: both 1.x and 2.4+ can be used. The current example works on 1.x with no changes. It works also on 2.4+ with manual addition of the device (thing) and the communication flows (channels), and some changes to the items part of the example.
Some openHAB users still run the 1.x binding and don't care about auto-discovery, they will find the current example as just what they need. The modified version is useless for them.
Other users do enjoy autodiscovery and no manual configuration, they will find the modified version more fit and palatable. They can still use the current example though with some manual intervention and knowledge of the internals, and modifying the code as it is.
Hope the scenario is a bit clearer now, that is why I thought of something like a branch, or a new example linked to the current one.

**Comment by rojer** [comment]
ok, so sounds like 1.x api is not on its way out and you say that supporting both in the same app is tricky.
so, maybe create `sonoff-basic-openhab2` for that? cross-reference the two from README and that's that. if you like, i can create `sonoff-basic-openhab2` and give you admin rights so you can create and maintain it.

**Comment by scaprile** [comment]
Oh, that would be great.

**Comment by rojer** [comment]
great. so i created https://github.com/mongoose-os-apps/sonoff-basic-openhab2 and added you as a maintainer. i also added you as a maintainer of this repo.

**Comment by scaprile** [comment]
Thanks!
